version: "3"
services:
  event-db:
    image: postgres
    container_name: "events"
    environment:
      - POSTGRES_USER=ana
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=events
    ports:
      - "5432:5432"
    volumes:
      - ./my-event-app:/var/lib/postgresql/data
